# Generated by Django 5.0 on 2024-01-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "layer_name",
                    models.CharField(max_length=300, verbose_name="Layer Name"),
                ),
                ("value", models.FloatField()),
                ("latitude", models.FloatField(verbose_name="Latitude")),
                ("longitude", models.FloatField(verbose_name="Longitude")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Recorded"
                    ),
                ),
            ],
        ),
    ]
